name: Ensure Code Owners Approve

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-approvals:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Code Owners Approval
        id: codeowners
        run: |
          # Define the code owners
          CODEOWNERS=("vinodjyadav" "rishabhvy") 

          # Get the list of approved users
          APPROVED_USERS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews" \
          | jq -r '.[] | select(.state == "APPROVED") | .user.login')

          # Initialize approval count
          APPROVAL_COUNT=0

          # Check if each code owner has approved
          for owner in "${CODEOWNERS[@]}"; do
            if echo "$APPROVED_USERS" | grep -qw "$owner"; then
              ((APPROVAL_COUNT++))
            fi
          done

          echo "Number of required code owner approvals: $APPROVAL_COUNT"

          # Set the approval count as an output for the next step
          echo "::set-output name=APPROVAL_COUNT::$APPROVAL_COUNT"

      - name: Fail the PR if not approved by both code owners
        if: steps.codeowners.outputs.APPROVAL_COUNT != '2'
        run: |
          echo "Not all required code owners have approved the PR."
          exit 1

      - name: Approvals Check Passed
        if: steps.codeowners.outputs.APPROVAL_COUNT == '2'
        run: echo "All required code owners have approved the PR."
